name: Run_app
env:
  APPLICATION_NAME: "Application"
  PACKAGE_NAME    : "app_ver_${{ github.sha }}"
    
on: 
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World Testing
      run: echo "Hello World Testing"

    - name: Print version
      run: |
        echo "Application name - ${{ env.APPLICATION_NAME}}"
        echo "Application version - ${{ env.PACKAGE_NAME }}"


  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print Hello World Deploy
      run: echo "Hello World Deploy"
    
