name: Run_app

on: 
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World Testing
      run: echo "Hello World Testing"


  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print Hello World Deploy
      run: echo "Hello World Deploy"
    
